### ISSUE TITLE
Typo de grammaire dans le texte

### ISSUE THREAD

**Issue by enguerran** [konnectors/ovh#20]
On devrait lire __Tout s'est bien passé__

![image](https://user-images.githubusercontent.com/701648/44530757-724f6300-a6ef-11e8-999f-bea86683977f.png)

**Comment by LucsT** [comment]
C'est une typo dans la traduction de l'appli collect, et non de ce connecteur.
Il faut le corriger dans transifex.

**Comment by enguerran** [comment]
fixed in https://github.com/cozy/cozy-home/issues/925
